In [ ]:
import numpy as np
import os
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.utils import np_utils # 여러가지 유틸을 사용하기 위한 유틸 다운

In [ ]:
np.random.seed(10)
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

In [ ]:
X_train = X_train.reshape(X_train.shape[0], 3072)
X_test = X_test.reshape(X_test.shape[0], 3072)

In [ ]:
# /255.0과 동일한 작업
X_train = (X_train - np.mean(X_train) / np.std(X_train))
X_test = (X_test - np.mean(X_test) / np.std(X_test))

In [ ]:
# 원 핫 벡터로 만들기 -> 이게 np.utils에 들어있는 거네
labels = 10

y_train = np_utils.to_categorical(y_train, labels)
y_test = np_utils.to_categorical(y_test, labels)
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense , Dropout

In [ ]:
input_layer = Input(shape=(3072,))
dense_layer_1 = Dense(512, activation="relu")(input_layer)
dropout_1 = Dropout(0.4)(dense_layer_1)


In [ ]:
dense_layer_2 = Dense(120, activation="relu")(dropout_1)
dropout_2 = Dropout(0.2)(dense_layer_2)

dense_layer_3 = Dense(labels, activation="sigmoid")(dropout_2)

model = Model(inputs=input_layer, outputs=dense_layer_3)

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 3072)]            0         
                                                                 
 dense (Dense)               (None, 512)               1573376   
                                                                 
 dropout (Dropout)           (None, 512)               0         
                                                                 
 dense_1 (Dense)             (None, 120)               61560     
                                                                 
 dropout_1 (Dropout)         (None, 120)               0         
                                                                 
 dense_2 (Dense)             (None, 10)                1210      
                                                                 
Total params: 1,636,146
Trainable params: 1,636,146
Non-train

In [ ]:
model.compile(loss = "categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
model.fit(X_train, y_train, batch_size=1000, epochs = 10, validation_data=(X_test, y_test))

Epoch 1/10
50/50 [==============================] - 8s 150ms/step - loss: 112.2413 - accuracy: 0.1169 - val_loss: 2.3033 - val_accuracy: 0.1018
Epoch 2/10
50/50 [==============================] - 7s 143ms/step - loss: 3.5592 - accuracy: 0.1095 - val_loss: 2.3028 - val_accuracy: 0.1000
Epoch 3/10
50/50 [==============================] - 7s 143ms/step - loss: 2.8514 - accuracy: 0.1055 - val_loss: 2.3028 - val_accuracy: 0.1000
Epoch 4/10
50/50 [==============================] - 7s 143ms/step - loss: 2.6352 - accuracy: 0.1024 - val_loss: 2.3027 - val_accuracy: 0.1000
Epoch 5/10
50/50 [==============================] - 7s 143ms/step - loss: 2.5240 - accuracy: 0.1022 - val_loss: 2.3027 - val_accuracy: 0.1000
Epoch 6/10
50/50 [==============================] - 7s 143ms/step - loss: 2.4742 - accuracy: 0.1011 - val_loss: 2.3027 - val_accuracy: 0.1000
Epoch 7/10
50/50 [==============================] - 7s 144ms/step - loss: 2.4480 - accuracy: 0.1002 - val_loss: 2.3026 - val_accuracy: 0.1000
Epoc

In [ ]:
loss, acc = model.evaluate(X_test, y_test)

313/313 [==============================] - 2s 5ms/step - loss: 2.3026 - accuracy: 0.1000


In [ ]:
print("loss = ", loss, "acc = ", acc)

loss =  2.3026137351989746 acc =  0.10000000149011612


In [ ]:
#ㅋㅋㅋㅋㅋㅋㅋㅋ이거 왜 그러냐
model.predict(X_test).argmax(axis=1)

array([4, 4, 4, ..., 4, 4, 4])

In [ ]:
model.save("model.h5")

In [ ]:
import keras.models

In [ ]:
model = keras.models.load_model("model.h5")

In [ ]:
loss, acc = model.evaluate(X_test, y_test)

313/313 [==============================] - 2s 5ms/step - loss: 2.3026 - accuracy: 0.1000


In [ ]:
model.predict(X_test).argmax(axis=1)

array([4, 4, 4, ..., 4, 4, 4])